<?php

namespace AppBundle\Repository;

/**
 * categoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriesRepository extends \Doctrine\ORM\EntityRepository {
    
    /**
     * Returns all categories of books.
     */
    public function getAll() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "SELECT c.id, c.name 
            FROM AppBundle:categories c");
        return $query->getResult();
    }
    
}
