<?php

namespace AppBundle\Repository;

/**
 * favoritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class favoritesRepository extends \Doctrine\ORM\EntityRepository
{
}
