<?php

namespace AppBundle\Repository;

/**
 * imagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imagesRepository extends \Doctrine\ORM\EntityRepository {
    
    /*
     * Returns all features for given tours.
     */
    public function findByBookIds($bookIds) {
        $em = $this->getEntityManager();
        $where = '';
        foreach ($bookIds as $bookId) {
            $where .= " OR i.books = $bookId";
        }
        $where = substr($where, 4);
        $query = $em->createQuery(
            "SELECT IDENTITY(i.books) AS bookId, i.name 
            FROM AppBundle:images i 
            WHERE $where"
        );
        return $query->getResult();        
    }
    
}
